### PR TITLE
Routing setup

### PR DESCRIPTION
**Pull request by ijsnow**
There are a lot of changes here, so you should pull from this branch and test it. I tested it all on my computer and there aren't any errors but it won't hurt for more testing. 

I added [kadira:flow-router](https://atmospherejs.com/kadira/flow-router) with [kadira:blaze-layout](https://github.com/kadirahq/blaze-layout) as well as [bootstrap-4](http://v4-alpha.getbootstrap.com/getting-started/introduction/) just for styling. 

I set up the router and made an example to show how everything works with making the GET request and publications and subscriptions.

### CODE REVIEW

**Comment by hjdarnel** [comment]
I'm testing this using the commands at the bottom of the request, under command line instructions-- 

git fetch origin
git checkout -b routing-setup origin/routing-setup
git merge master

This should checkout the routing branch, merge it into master (as though we merged the pull request, but local), and switch to that branch. Then just run meteor and open a web page

**Comment by hjdarnel** [comment]
When I try to run just the branch, without merging it, I get a ReferenceError: FlowRouter isn't defined. Any idea? Maybe I'm testing it wrong.

**Comment by ijsnow** [comment]
Look in the .meteor/packages file. There should be a line that says
kadira:flow-router

**Comment by hjdarnel** [comment]
That makes sense. It worked

**Comment by ijsnow** [comment]
I wonder why it wasn't in there already though because I put it in there

**Comment by hjdarnel** [comment]
.meteor is probably in your gitignore

**Comment by ijsnow** [comment]
No I looked at that one time. Just the local directory in there is ignored.
I'll check if for some reason I didn't commit that or there could have been
some kind of merge error

**Comment by ijsnow** [comment]
Hmm. Looks like it didn't get added for some reason. I'll commit it again.

**Comment by ijsnow** [comment]
The layout package got left out as well. And this is why we do pull requests and tests!

**Pull request closed without merging**
