### PR TITLE
Incorporate current transaction entries on product search page

### PR DESCRIPTION
**Pull request by hjdarnel**
Here I created template `{{> currentTransactionEntries}}` that just `find()` on TransactionEntries collection and displays it (currently just in a `<ul>`). I also brought out the code we had for the product search field, and put it in a template `{{> searchProduct}}`. Each of these have their own folder now with the respective helper functions. In the home template, this now simply calls both of the templates. This probably needs to be _renamed_ to match its final purpose, which we can do later.

Note: for testing I created a dummy TransactionEntries entry using `meteor mongo` from the terminal, so TransactionEntryLogic.js changes haven't been tested.

### CODE REVIEW

**Comment by ijsnow** [comment]
So is the `currentTransactionEntries` template supposed to display all of the transaction entries or the entries being made for the transaction that we are making at that point in time?

**Comment by hjdarnel** [comment]
The transaction entries table should only be filled with the current entries, is how I understood it. So once you tender and complete a transaction that table should be cleared

**Comment by ijsnow** [comment]
Are you sure? That doesn't sound right to me. What if there are multiple cashiers making a transaction at the same time?

**Comment by hjdarnel** [comment]
Okay, so maybe that's not how we should do it (though I think we could.) Instead it should find where the transaction ID is equal to the current transaction. Where are we setting the current transaction though?

**Comment by ijsnow** [comment]
I'm not sure that we could do it that way using just a find. How do you suppose we could? 

We could check for the ones with the transaction ID of the current transaction if it existed. From my understanding though, none of these exist in the collections until the transaction is completed.

**Comment by hjdarnel** [comment]
What I was thinking is that the transactionentries table would hold the products and quantities until the transaction was completed, where details are written to the transactions table. This wouldn't leave any kind of log of which products/quantities on which transaction, so that wouldn't be good. Hmm.

**Comment by ijsnow** [comment]
Yea I think we only write to the DB's when the transaction is completed. Think of something that we can store info in on only the client that will stick through page reloads and multiple tabs.

**Comment by hjdarnel** [comment]
I mean we could just set a session variable that is set when the cashier navigates from the landing page to the add product/add tender page and is cleared when the transaction is completed? Might need to ask Dr. Phillips

**Comment by ijsnow** [comment]
I don't think we need to ask Dr. Phillips. That's what we need to do. That's how carts and stuff are done on ecommerce sites which is basically what we are doing here. You can read about Sessions in meteor [here](http://docs.meteor.com/#/full/session)

**Comment by willpoorman** [comment]
I am just now looking over all this so I can't really be certain but from your guys' comments I'm pretty sure we should do it like Isaac is talking about

**Comment by hjdarnel** [comment]
Sorry @willpoorman it also gets confusing because GitHub include commit comments. Haha. So if I'm understanding correctly, we need to randomly create a transaction ID when the transaction is opened, set a session variable to that ID, and clear it when the transaction is completed. This ID will be tied to the Transaction Entries

**Comment by ijsnow** [comment]
Well there are probably multiple ways to do this. I think we should leave the ID generation to mongo though. In my opinion the simplest and safest way to do this would be to store everything that has to do with the current transaction in session variables and then once the transaction is complete, we create the transaction in the transactions collection and use the ID we get from that with the transaction entries we have and put those into that collection. This way if for whatever reason the transaction is canceled we don't have to delete the transaction entries we already entered or we don't have just random entries floating around out there.

**Pull request merged**
